db = [
    'The teacher looked at his gaping shoes and tattered clothes and knew she had to find out what was really going on at home or this kid would end up in the system. She called him up to her desk and asked, "Do you want to help me on a project this weekend?"',
    "It wasn't a happy winter, but it wasn't so sad either, considering.",
    "A parole officer falls in love with his parolee.",
    "The dog raced toward her with such intensity that she didn't have time to get out of his way.",
    "Your main character has just come face to face with their worst enemy, and they are monologuing.",
    "When they inspected Lesley Olson's passport, she never expected they would...",
    '"One of us has to try it," Amir said as he pointed to the lumpy, unfamiliar fruit on the tree in front of them. If we don\'t, we\'ll starve to death. Death by poison seems worth the risk in case it\'s edible, doesn\'t it?"',
    "She kept picking at it. First her index finger to gain entry. Followed by all of them. Digging deeper and deeper, despite the increasing pain. Logically, she knew she should stop, but it kept...",
    'Your main character joins the communist regime and leads the party to glorious victory over the capitalist bourgeoisie funded by your antagonist\'s Super-PAC.',
    '"As you\'re paying for your groceries, you allude to the clerk, "There\'s a mess in aisle 16." They give you a puzzled see and reply, "There is no aisle 16."',
    "A group of friends steal a neighbor's watermelon and find ways to frame other people.",
    "You get to make one wish to create your dream romantic partner. What is it?",
    "Your character's first-grade teacher leaves in the middle of the year, and her husband replaces her but offers no explanation.",
    "What makes you a religious or spiritual person?",
    "What is the difference in good versus evil? How do you know?",
    "Spend 24 hours locked in the old insane asylum and win a million dollars. It's been 26 hours, so why is the door still locked?",
    "A child draws scenes that end up happening exactly as he/she draws them. His/her parents try to understand what is happening.",
    "45 minutes ago my cover was blown. I'd been under for...",
    "An American actor is cast as the star of a movie about a multi-lingual travel agent. Instead of buying Rosetta Stone, he packs his bags and decides to travel to four different countries across the world, but he doesn't expect to fall in esteem with his guide.",
    "The False Light Gods: A group of evil entities attempt to trick people into believing they are the good guys by disguising themselves as saints, angels, gods, and goddesses.",
]